[package]
name = "mealy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
stateright = "0.30.0"
choice = { version = "0.0.2", features = ["serde"] }